### ISSUE TITLE
Resize VBox Image

### ISSUE THREAD

**Issue by thermokarst** [qiime2/playbooks#12]
Maybe this should be a dynamically allocated disk, say 500 GB?

Resizing a VMDK is a [major pain](https://forum.qiime2.org/t/no-disk-space-on-virtual-box/228/2).

**Comment by jairideout** [comment]
👍 , it'd be great to avoid resizing. @gregcaporaso do you recall how we handled this for QIIME 1 VB? I don't remember this being an issue with those VBs.

**Comment by gregcaporaso** [comment]
For QIIME 1 we used dynamically allocated storage:

![screenshot 2017-01-06 14 39 45](https://cloud.githubusercontent.com/assets/192372/21733905/048f571c-d41e-11e6-93c5-3e7077cff1da.png)

**Comment by thermokarst** [comment]
Thanks @gregcaporaso, the Q2 image is also a dynamically allocated storage device. The problem is at the time of baking, you have to specify a max value. Looks like ours was set way too small. Any guess as to how big the QIIME 1 image is? You could do a `df` in the machine (I don't have a QIIME 1.9 image available, and with my awesome slow internet...)

**Comment by gregcaporaso** [comment]
Looks like it was 200GB for the QIIME 1 VBs.
